### ISSUE TITLE
link error master

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1043]
Hi, I wonder how this slipped through, but seems like the last PR did not compile?

```
/elektra-clang/build/src/plugins/fcrypt    -fPIC -o CMakeFiles/elektra-fcrypt-objects.dir/__/crypto/helper.c.o   -c /home/jenkins/workspace/workspace/elektra-clang/src/plugins/crypto/helper.c
/home/jenkins/workspace/workspace/elektra-clang/src/plugins/crypto/helper.c:13:10: fatal error: 'base64_functions.h' file not found
#include <base64_functions.h>
         ^
```

**Comment by petermax2** [comment]
Oh boy, I thought I fixed this issue. CMake had problems with the include paths. It was initially working on version 3.6.2 but not on older ones like Debian's 3.0.2. I found a solution that worked for all of my VMs and the default build jobs.

**Comment by petermax2** [comment]
I can reproduce the error on my Debian VM following the commands on the build server.

**Comment by markus2330** [comment]
Ok, thanks for your quick response!

Is the problem caused by the combination of the two PRs?

**Comment by petermax2** [comment]
> Is the problem caused by the combination of the two PRs?

Yes, `fcrypt` includes the GPG interface of `crypto` which now relies on `base64`. What could possibly go wrong with this combination? 😆  

I fixed it. PR is coming up soon.

**Comment by markus2330** [comment]
Thank you!

**Comment by markus2330** [comment]
Seems to be still not fully fixed:

```
/home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/base64/base64_functions.c:22: multiple definition of `libelektra_ELEKTRA_PLUGIN_NAME_C_LTX_elektraPluginbase64Encode'
../../plugins/base64/CMakeFiles/elektra-base64-objects.dir/base64_functions.c.o:/home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/base64/base64_functions.c:22: first defined here
../../plugins/fcrypt/CMakeFiles/elektra-fcrypt-objects.dir/__/base64/base64_functions.c.o: In function `libelektra_ELEKTRA_PLUGIN_NAME_C_LTX_elektraPluginbase64Decode':
/home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/base64/base64_functions.c:103: multiple definition of `libelektra_ELEKTRA_PLUGIN_NAME_C_LTX_elektraPluginbase64Decode'
../../plugins/base64/CMakeFiles/elektra-base64-objects.dir/base64_functions.c.o:/home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/base64/base64_functions.c:103: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by markus2330** [comment]
Btw. as long term goal it would be great if there are less dependencies between the plugins, in particular not transitive ones (and cyclic ones are a no-go).

**Comment by petermax2** [comment]
@markus2330 which of the build jobs produced the output above? Guessing from the output it must be a statically linked build.

**Comment by petermax2** [comment]
It was `elektra-git-buildpackage-wheezy`

**Comment by markus2330** [comment]
Jessie is affected, too http://community.markus-raab.org:8080/job/elektra-git-buildpackage-jessie/lastFailedBuild/console

**Comment by petermax2** [comment]
For some reason the `COMPILE_DEFINITION` argument `ELEKTRA_PLUGIN_NAME_C` is not propagated to the plugins source.

**Comment by markus2330** [comment]
Might be a problem in `cmake/Modules/LibAddPlugin.cmake`?

**Comment by petermax2** [comment]
CMake call to reproduce:

    cmake -DCMAKE_INSTALL_PREFIX=/usr -DTARGET_PLUGIN_FOLDER=elektra4 -DPLUGINS="'ALL;-EXPERIMENTAL;-python;mozprefs;c;simplespeclang;base64;fcrypt'" -DTOOLS="'ALL'" -DBINDINGS="'cpp;swig_lua;swig_python2;intercept'" -DKDB_DB_SYSTEM:PATH="/etc/kdb" -DKDB_DB_HOME:PATH="/home" -DKDB_DB_USER:PATH=".config" -DINSTALL_DOCUMENTATION=ON -DTARGET_DOCUMENTATION_HTML_FOLDER=share/doc/libelektra-doc/html -DSWIG_EXECUTABLE=/usr/bin/swig3.0 -DENABLE_TESTING=ON -DINSTALL_TESTING=ON -DENABLE_KDB_TESTING=OFF -DBUILD_PDF=OFF -DBUILD_FULL=ON -DBUILD_STATIC=ON -DTARGET_TEST_DATA_FOLDER=share/libelektra-test/test-data -DCMAKE_C_FLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2" -DCMAKE_CXX_FLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2" -DCMAKE_EXE_LINKER_FLAGS="-Wl,-z,relro" -DCMAKE_MODULE_LINKER_FLAGS="-Wl,-z,relro" -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,relro" ..

**Comment by markus2330** [comment]
Anything with ENABLE_STATIC=ON and containing the base64 plugin should do, shouldn't it?

**Comment by petermax2** [comment]
> Anything with ENABLE_STATIC=ON and containing the base64 plugin should do, shouldn't it?

Only with `fcrypt` enabled too. I wonder if it fails because fcrypt does not use compile variants.

**Comment by petermax2** [comment]
Where exactly in `CMakeLibAddPlugin.cmake` / `add_plugin` are the COMPILE_ARGS made available to the source code? 

I can track that they are set correctly by adding `message (DEBUG, "${PLUGIN_NAME}: COMPILE_ARGS are ${ARG_COMPILE_DEFINITIONS}")` to the function. But they do not seem to get passed on to the preprocessor.

**Comment by markus2330** [comment]
The set_property statements do it: lines 360 and 404 in cmake/Modules/LibAddPlugin.cmake

It seems like the best fix is to remove the transitive dependency. An error that depends on which plugins are selected additionally is quite weird.

**Comment by petermax2** [comment]
> It seems like the best fix is to remove the transitive dependency. An error that depends on which plugins are selected additionally is quite weird.

I agree. Maybe re-using (and thus re-compiling) other plugins' code is not the best way to achieve modularity. Maybe we can use the dlloader to re-use other plugins functions?

**Comment by markus2330** [comment]
The libraries are the way to go! See `src/libs/`, e.g. libease might be a fit for some functionality.

In the case of base64_functions.c I wonder why it gets pulled into fcrypt at all. It is somehow understandable that crypto uses it to encode its configuration (unfortunately (currently) for plugin configuration other plugins cannot be used).

But as you know during runtime you can also define dependencies between plugins using the contract (ensure that a plugin is there if needed). So if you want encrypted files to be base64 encoded, you would add a new feature in the base64 plugin to also encode whole files and mount it additionally to `fcrypt` (if needed). So for base64 functionality there should (currently) not be a need to move it to libs.

So the easiest fix seems to clean up gpg.h to not pull in things not needed?

**Comment by petermax2** [comment]
I have another idea, let's see if it works.

**Comment by markus2330** [comment]
It was a good idea, it has fixed the problem!

Thank you!

I will close the issue, please reopen other issues if you need them for cleanup tasks we discussed.
