### ISSUE TITLE
lua test case fails when lua-bindings are installed

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#383]
Hello,

 ctest -V -R testmod_lua runs fine unless I install libelektra-lua4 which contains /usr/lib/lua/5.2/kdb.so

Suddenly I get:
```
32: Test command: /home/markus/Projekte/Elektra/build/bin/testmod_lua "/home/markus/Projekte/Elektra/current/src/plugins/lua"
32: Test timeout computed to be: 1500
32: LUA         TESTS
32: ==================
32: 
32: Testing simple variable passing...
32: [LUA-1] open -->
32: [LUA-1] get
32: /home/markus/Projekte/Elektra/current/src/plugins/lua/testmod_lua.c:26: error in test_variable_passing: call to kdbGet was not successful
32: /home/markus/Projekte/Elektra/current/src/plugins/lua/testmod_lua.c:27: error in test_variable_passing: keyset size is still 0
32: /home/markus/Projekte/Elektra/current/src/plugins/lua/testmod_lua.c:28: error in test_variable_passing: key in keyset has wrong name
32: [LUA-1] <-- close
32: Testing loading of two active lua plugins...
```

The problems seems to be that immediately when parentKey.name is accessed there is an lua error, thus the key is not appended.

On my system lua5.1 and lua5.2 is installed (lua 5.2 is used). The installed package (kdb.so) was built on your agent.

**Comment by manuelm** [comment]
I don't have any debian system nor do I have lua 5.1. So you're on your own to provide more debugging information. e.g. which shared object gets loaded and what's the error message in detail.

**Comment by manuelm** [comment]
FYI: The lua plugin loads the lua bindings package. Lua, like any other language, starts searching for packages in the systemwide locations, unless otherwise specified. So the installed lua bindings gets loaded and for whatever reason it's not (maybe binary?) compatible with your testmod_lua.
But there's nothing I can do about it.

You can override the search path with the LUA_CPATH env. variable.

**Comment by markus2330** [comment]
I uninstalled 5.1. Problem still there.

```
ldd /usr/lib/lua/5.2/kdb.so | grep lua
        liblua5.2.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007f3726e29000)
ldd /home/markus/Projekte/Elektra/build/bin/testmod_lua
        liblua5.2.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007fbf4af2b000)
```

The system wide kdb.so is used (w and w/o LUA_CPATH):
```
open("/usr/lib/lua/5.2/kdb.so", O_RDONLY) = 3
src/plugins/lua> LUA_CPATH=. strace ~build/bin/testmod_lua ~e/src/plugins/lua
open("/usr/lib/lua/5.2/kdb.so", O_RDONLY) = 3
```

I am mainly interested why the unit test fails. Is it possible to output the lua error?

**Comment by manuelm** [comment]
wrong `LUA_CPATH` syntax. You need to specify the full path with `?` as placeholder e.g. `LUA_CPATH=./?.so`

as far as I remember the error should be printed. I'm catching any error and setting `ELEKTRA_SET_ERROR`. The rest should be handled by your test framework.

**Comment by manuelm** [comment]
Have you built the elektra plugin using the same swig version as the build agent? Both binding and plugin depend on swig and it's generated interface structure, so this might be an issue.

**Comment by markus2330** [comment]
No error is set in this case.

In the lua's plugin code, there will be no set error if lua_isnil is true.

I will leave it for this release as is. It works quite well (I could mount a plugin). This problem seems to be minor.

I dont know the exact version on the build agent, thats why I asked in the beginning.

**Comment by manuelm** [comment]
2.0.12 and 3.0.2 but I'm sure you'll find the version information in the jenkins log too :-)

**Comment by markus2330** [comment]
I think 2.0 will be preferred then.. I did not find a way to specify SWIG_EXECUTABLE for jessie but not for wheezy...

**Comment by manuelm** [comment]
Btw: You're looking at the wrong code section. lua_isnil is only true if the plugin is unable to get a new lua state/instance.
It's https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/lua/lua.cpp#L77 in which you're interested.

**Comment by markus2330** [comment]
Yeah, I was looking on a random place. Nevertheless, a plugin should always set an error if it returns -1.

**Comment by manuelm** [comment]
That's the case anyway.

**Comment by markus2330** [comment]
So, test cases our now fixed and output the errors. Do you have an idea?

```
number: 131
description: : lua error
ingroup: : plugin
module: : lua
at: /home/markus/Projekte/Elektra/current/src/plugins/lua/lua.cpp:78
reason: : ...jekte/Elektra/current/src/plugins/lua/lua/lua_plugin.lua:10: attempt to index local 'parentKey' (a userdata value)
mountpoint: : user/from_c
configfile: : 
/home/markus/Projekte/Elektra/current/src/plugins/lua/testmod_lua.c:30: error in test_variable_passing: errors in kdbOpen
```

**Comment by manuelm** [comment]
looks like broken swig resolving to me. parentKey is missing it's interface.
You can try to add a `print(kdb)` + `print(kdb.Key)`  to the top of `lua_plugin.lua` to gain more information but I doubt there's something you can fix.

**Comment by markus2330** [comment]
Amazing that you can draw a connection of `attempt to index local` to swig.

Why not deinstall swig2.0 on the jessie-agent, isn't that the easiest fix?

**Comment by manuelm** [comment]
In lua every external object is userdata unless you provide lua with information about it. That's missing :-)

I'm all for deprecating swig2. You were the one that still want to support it.

**Comment by markus2330** [comment]
Its needed for wheezy. And it also works there. But why is it installed on the jessie agent?

**Comment by manuelm** [comment]
I guess you got my comment wrong. I've two build agents, thus two versions. In detail:
```
$ ssh ... "cat /etc/debian_version && swig -version"
8.2

SWIG Version 2.0.12

$ ssh ... "cat /etc/debian_version && swig -version"
stretch/sid

SWIG Version 3.0.2
```

**Comment by markus2330** [comment]
Ok, please update it then. SWIG2 is known not to work on jessie (debian 8.2)

**Comment by manuelm** [comment]
Which package shall I use? swig2 is the one in the official repos

**Comment by markus2330** [comment]
swig3.0 works well here. So this might work:

     apt-get install swig3.0 swig- swig2.0-

Which agent is used for the elektra-test-bindings?

**Comment by manuelm** [comment]
swig replacement done. forgot that it's named swig3.0…

afaik all bindings stuff is sid only

**Comment by markus2330** [comment]
Thank you, agent is building.

**Comment by markus2330** [comment]
very strange, I still have same problem even though the testcase runs with `kdb  testmod_lua`, but not in-source.
