### ISSUE TITLE
debian: errors installing+using

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1432]
The build server finally built https://build.libelektra.org/job/elektra-git-buildpackage-jessie/lastSuccessfulBuild/console

:+1: 

Unfortunately, there are errors in installing:

```
Preparing to unpack .../elektra-qt-gui_0.8.19-1.5721_amd64.deb ...
Unpacking elektra-qt-gui (0.8.19-1.5721) ...
dpkg: error processing archive /var/cache/apt/archives/elektra-qt-gui_0.8.19-1.5721_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/kdb-qt-gui.1.gz', which is also in package elektra-bin 0.8.19-1.5721
Processing triggers for man-db (2.7.0.2-5) ...
Errors were encountered while processing:
 /var/cache/apt/archives/elektra-qt-gui_0.8.19-1.5721_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Press Return to continue.
```

and install-docs fails:

```
install-docs --verbose --check /usr/share/doc-base/elektra-doc
Warning in `/usr/share/doc-base/elektra-doc', line 8: file `/usr/share/doc/elektra-doc/html/index.html' does not exist.
Error in `/usr/share/doc-base/elektra-doc', line 8: all `Format' sections are invalid.
/usr/share/doc-base/elektra-doc: Fatal error found, the file won't be registered.
```

and using it with cmake fails, too (can be tested with `ctest -V -R external` which runs `cmake` in the `examples/external/cmake` project):

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Elektra/ElektraTargetsLibelektra.cmake:98 (message):
  The imported target "elektra-utility" references the file

     "/usr/lib/x86_64-linux-gnu/libelektra-utility.so.0.8.19"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/Elektra/ElektraTargetsLibelektra.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Elektra/ElektraConfig.cmake:16 (include)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred
```

Btw. at least aptitude needed a lot of help to upgrade to the new packages.
Can you test on PCS?

Thank you, great job nevertheless. It is very nice to have debug symbols and hopefully also the qt-gui soon ;)

**Comment by markus2330** [comment]
And not to forget the many new plugins that were added!

:+1: 

There seem to be some more files missing for testmod_blockresolver testmod_crypto_botan testmod_crypto_gcrypt testmod_crypto_openssl testmod_file testmod_mozprefs testmod_passwd test_utility

(Simply run `kdb run-all` to see the errors)

Is all test data installed?
```
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/file/testmod_file.c:27: error in testReadSingleLine: call to kdbGet was not successful
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/file/testmod_file.c:30: fatal in testReadSingleLine: key not found
error: testmod_file
```

Some plugins seem to be not installed, too?
```
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/crypto/test_internals.h:116: error in test_init: failed to open the plugin
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/crypto/test_internals.h:152: error in test_incomplete_config: failed to open the plugin
```

Btw. it is enough if master builds with it, you cannot have both (0.8.19 and master).

**Comment by reox** [comment]
Seems like the install flles are a little bit messed up... I removed the * import in the elektra-bin.install, and saw that there are two manpages, where I have no clue if they should go into the bin package:
usr/share/man/man1/kdb-introduction.1
usr/share/man/man1/kdb-elektrify-getenv.1

For the rest, i need to take a closer look...

**Comment by markus2330** [comment]
> kdb-introduction.1

Is referred from `kdb.1`, so it should be in the same package.

> kdb-elektrify-getenv.1

In the same package as the script `elektrify-getenv`?

> For the rest, i need to take a closer look...

Thank you!

**Comment by reox** [comment]
I think i fixed the bugs, at least I can install everything...
`kdb run-all` does not exists? Also how do i run `ctest -V -R external`? for me this does nothing...

the libelektra-utility seems to be not installed: `for x in *.deb; do dpkg --contents $x; done | grep utility` is empty. For the plugins: I use `ELEKTRA_PLUGINS='ALL;mozprefs;multifile'` - it seems there are plugins that are neither in ALL nor in EXPERIMENTAL (such as multifile). I think it would be better to fix it there rather than in the rules file?

**Comment by reox** [comment]
I saw that the libelektra-gen package seems to be not replaced by anything. Some of the files (python support) are in the python-elektra package, which seems to be wrong? And the templates are not installed at all... Should I create a new libelektra4-gen package?

**Comment by markus2330** [comment]
> kdb run-all does not exists?

Sorry, `run_all` part of the package `elektra-tests` (script is in `/usr/lib/x86_64-linux-gnu/elektra/tool_exec/run_all`). So `kdb run_all` should work if `elektra-tests` is installed.

> Also how do i run ctest -V -R external? for me this does nothing...

This needs to be done from the build directory. `mkdir build && cmake <source dir> && ctest -V -R external`

> the libelektra-utility seems to be not installed

That is a new library (master), which gets installed to `lib/libelektra-utility.so*` (with version information as for other libs).

> I think it would be better to fix it there rather than in the rules file?

Where is mozprefs or multifile not compiled/installed? Locally and on the [build server](https://build.libelektra.org/job/elektra-git-buildpackage-jessie/lastSuccessfulBuild/consoleFull) they are built with `ALL`. The issue is that `usr/share/libelektra-test/test-data/file/multiline` is not installed, causing the test to fail. They are listed in `dh_install --list-missing`

> Should I create a new libelektra4-gen package?

Yes, please.

**Comment by reox** [comment]
`run_all RESULTS: 123 test(s) done 0 error(s).`

But i needed to use dh-exec to rename the doc folder, which breaks dh_install --list-missing: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831786
But the list while the buildpackage only contains gtest files and the egg-info, which is not needed:
```
dh_install --list-missing
dh_install: usr/lib/libgtest_main.a exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/libgtest.a exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/elektra_gen-0.8.19.egg-info exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest-typed-test.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest-param-test.h.pump exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest-test-part.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest-printers.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest_pred_impl.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest-death-test.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest-param-test.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest-spi.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest_prod.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/gtest-message.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-death-test-internal.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-param-util.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-port-arch.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-filepath.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-tuple.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-param-util-generated.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-type-util.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-param-util-generated.h.pump exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-string.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-port.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-tuple.h.pump exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-type-util.h.pump exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-internal.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/gtest-linked_ptr.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/custom/gtest.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/custom/gtest-printers.h exists in debian/tmp but is not installed to anywhere
dh_install: usr/include/gtest/internal/custom/gtest-port.h exists in debian/tmp but is not installed to anywhere
```

Does the jenkins something else?
I use this script now to build from master:
```
#!/bin/bash
set -e
set -x

VERSION="0.8.19"
BUILD_NUMBER="1337"

[ -d tmpbuilddir ] && rm -rf tmpbuilddir

mkdir tmpbuilddir

cd tmpbuilddir
git clone https://github.com/reox/libelektra -b master
cd libelektra
git remote add upstream https://github.com/ElektraInitiative/libelektra.git

git fetch upstream/master || :
git merge --no-ff -m "merge $VERSION" upstream/master || :
git tag -f $VERSION

git checkout -b debian origin/debian
git merge --no-ff -m "merge $VERSION" master

dch -l ".$BUILD_NUMBER" "auto build"

git commit -am "auto build $VERSION"

git archive --format=tar HEAD | gzip > ../elektra_$VERSION.orig.tar.gz

dpkg-buildpackage
```

**Comment by markus2330** [comment]
> run_all RESULTS: 123 test(s) done 0 error(s).

It should be 128 (8 of them failing)? Maybe you have some dependencies not installed and some of the plugins get not included when you build it? The deps should be added in the `control` file.

Did you try installing Elektra's packages from the build server?

> dh_install --list-missing
> gtest..

Yes, not installing gtest is okay. Debian's gtest produces some warnings and tries to install files not needed.

> Does the jenkins something else?

https://build.libelektra.org/job/elektra-git-buildpackage-jessie/lastSuccessfulBuild/consoleFull logs every step it does.

**Comment by reox** [comment]
> https://build.libelektra.org/job/elektra-git-buildpackage-jessie/lastSuccessfulBuild/consoleFull logs every step it does.

Ahh I see... yes, there are unmet dependencies for the packages. The only thing I could not find is `jni`

**Comment by markus2330** [comment]
> libssl-dev does not resolve the dependencies for cryto_openssl

Can you post the cmake output and the relevant content of CMakeCache.txt?
@petermax2 do you have some idea? Have you tried compiling with stretch?

> I'm building on stretch, the buildserver seems to use jessie, is this a problem?

No issue at all, both should work. You can think of the jessie build as a backport. I'll set up a stretch build later.

**Comment by reox** [comment]
https://files.reox.at/buildlog.txt

and a list of manual installed packages in the build vm:
```
acpid adduser apt apt-utils base-files base-passwd bash bsdmainutils bsdutils build-essential cmake coreutils cpio cron dash debconf debconf-i18n debian-archive-keyring debianutils devscripts dh-exec dh-lua diffutils discount dmidecode dmsetup doxygen dpkg e2fslibs e2fsprogs findutils gcc-6-base gettext-base git git-buildpackage gnupg gnupg-agent gpgv graphviz grep grub-common grub-pc grub-pc-bin grub2-common gzip hostname htop ifupdown init init-system-helpers initramfs-tools initramfs-tools-core iproute2 iptables iputils-ping isc-dhcp-client isc-dhcp-common klibc-utils kmod libacl1 libapparmor1 libapt-inst2.0 libapt-pkg5.0 libassuan0 libattr1 libaudit-common libaudit1 libaugeas-dev libblkid1 libboost-dev libbotan1.10-dev libbsd0 libbz2-1.0 libc-bin libc6 libcap-ng0 libcap2 libcomerr2 libcryptsetup4 libcurl4-gnutls-dev libdb5.3 libdbus-1-dev libdebconfclient0 libdevmapper1.02.1 libdns-export162 libedit2 libelf1 libestr0 libfastjson4 libfdisk1 libffi6 libfreetype6 libfuse2 libgcc1 libgcrypt20 libgcrypt20-dev libgdbm3 libgit2-dev libgmp10 libgnutls30 libgpg-error0 libgpm2 libgssapi-krb5-2 libgtest-dev libhogweed4 libidn11 libidn2-0 libip4tc0 libip6tc0 libiptc0 libisc-export160 libk5crypto3 libkeyutils1 libklibc libkmod2 libkrb5-3 libkrb5support0 libksba8 liblocale-gettext-perl liblogging-stdlog0 liblognorm5 liblua5.2-dev liblz4-1 liblzma5 libmarkdown2-dev libmnl0 libmount1 libncurses5 libncursesw5 libnetfilter-conntrack3 libnettle6 libnewt0.52 libnfnetlink0 libnpth0 libp11-kit0 libpam-modules libpam-modules-bin libpam-runtime libpam0g libpcre3 libpipeline1 libpng16-16 libpopt0 libprocps6 libpsl5 libreadline7 libseccomp2 libselinux1 libsemanage-common libsemanage1 libsepol1 libslang2 libsmartcols1 libsqlite3-0 libss2 libssl-dev libssl1.0.2 libssl1.1 libstdc++6 libsystemd-dev libsystemd0 libtasn1-6 libtext-charwidth-perl libtext-iconv-perl libtext-wrapi18n-perl libtinfo5 libudev1 libunistring0 libustr-1.0-1 libuuid1 libwrap0 libxapian30 libxml2-dev libxtables12 libyajl-dev linux-base linux-image-4.9.0-2-amd64 linux-image-amd64 locales login logrotate lsb-base mawk mount multiarch-support nano ncurses-base ncurses-bin netbase openjdk-8-jdk openjdk-8-jdk-headless openssh-client openssh-server openssh-sftp-server openssl passwd perl-base pinentry-curses pkg-config procps python-cheetah python-dev python2.7-dev python3-dev qtbase5-dev qtdeclarative5-dev readline-common rsyslog ruby-ronn sed sensible-utils sudo swig3.0 systemd systemd-sysv sysvinit-utils tar tasksel tasksel-data tree tzdata ucf udev util-linux vim vim-common vim-runtime vim-tiny wget whiptail xxd zlib1g
```

**Comment by markus2330** [comment]
Thanks! Can you please create a PR of the fixes you have done so far?

Could you reproduce the external cmake project problem?

**Comment by reox** [comment]
It seems like, it fails now because of the dependencies:
`dpkg-checkbuilddeps: Unmet build dependencies: dh-exec libcurl4-gnutls-dev openjdk-8-jdk`

dh-exec is needed to rename files. What about java? I can change that to accept another java version as well. What dependencie do you use for libcurl? For me this one was required...

**Comment by reox** [comment]
For the openssl: It seems this is a jessie/stretch problem. On jessie crypt_openssl is included!

**Comment by markus2330** [comment]
Thanks for investigating!

For jessie/stretch (or other) conflicts you can simply specify both as option.

For libcurl `libcurl4-openssl-dev` is installed (but maybe it works with other libcurl variants too, best to specify all? What are other packages (depending on libcurl) doing?)

For java we use `oracle-java8-installer`, see src/plugins/jni/README.md. Maybe `oracle-java8-jre` or `oracle-java8-jdk`; or even the more generic `java8-jdk` or `java8-sdk`; is more suitable as dependency? (It is provided by `oracle-java8-installer`).

dh-exec is now installed.

**Comment by markus2330** [comment]
More challenging are gitresolver and ruby which deps are not available at jessie. So `usr/lib/*/elektra4/libelektra-gitresolver.so` either is installed or is not (depending on jessie/stretch).

So with jessie the build currently fails at:
```
dh_install: libelektra4 missing files (usr/lib/*/elektra4/libelektra-gitresolver.so), aborting
```

So either we

1. depend on backports for swig and libgit2,
2. simply drop gitresolver and ruby from the packages for now, or
3. find a way how to conditionally install it?

**Comment by reox** [comment]
weird - I can not use the build-depends line `java7-jdk  | java8-jdk` because i get the error that those packages are not installed, allthough `default-jdk` should provide them. Anyone has an idea?

**Comment by markus2330** [comment]
Why not simply use
```
openjdk-8-jdk | java8-jdk | oracle-java8-installer,
```
Then every situation should be covered?

**Comment by reox** [comment]
> Then every situation should be covered?

java8-jdk should be the correct package, but it does not work... so I use now all three.

**Comment by markus2330** [comment]
For libcurl every packages depending on curl seems to depend on a different constellation of curl variants? From a quick look-through

`libcurl4-nss-dev | libcurl4-gnutls-dev | libcurl4-openssl-dev | libcurl-dev`

might be the superset. I do not see a reason why Elektra would need a specific variant, it should work with any. But what would the debian build agents install if we specify everything?

**Comment by reox** [comment]
for the openssl problem: I think the problem is the script that is tried to compile:
```
vmmanage@build-stretch-amd64:~/tmpbuilddir/libelektra/src/plugins/crypto$ gcc compile_openssl.c 
compile_openssl.c: In function ‘main’:
compile_openssl.c:14:17: error: storage size of ‘opensslSpecificType’ isn’t known
  EVP_CIPHER_CTX opensslSpecificType;
                 ^~~~~~~~~~~~~~~~~~~
```
It does not compile on my stretch VM. On jessie it works.
I think they changed the Openssl api from 1.0.1 to 1.1.0...

**Comment by markus2330** [comment]
Really great work, everything works like a charm now! Installation of Elektra (with qt-gui!) never has been easier!

I did some micro fixes to get it building on jessie, I might have broken stretch while doing so. Please feel free to overwrite the changes with the next PR (#1437)

**Comment by reox** [comment]
More problems: The python3 version is quite old:
```
The following packages have unmet dependencies:
 libelektra4 : Depends: libpython3.4 (>= 3.4.2~rc1) but it is not going to be installed
 libelektra4-python : Depends: libpython3.4 (>= 3.4.2~rc1) but it is not going to be installed
 python3-elektra : Depends: libpython3.4 (>= 3.4.2~rc1) but it is not going to be installed
                   Depends: python3 (< 3.5) but 3.5.3-1 is to be installed
```

I think this is a jessie dependency?

**Comment by markus2330** [comment]
Elektra's python binding should work with any version of python 3. (At least no issue was found or reported.) On Debian, however, you sometimes need to specify paths to python interpreters/libraries (see `src/bindings/swig/python/README.md`). So maybe the specific request to `python3.4` was done so that it is found by cmake out of the box.

**Comment by reox** [comment]
I think the problem here is, that the ${python3:Depends} variable sets this automatically, as python 3.4 is the default in jessie. I think it is required to build for each release seperately?
For example, on a stretch machine, those dependencies are added:  
```Depends: libelektra4 (= 0.8.19-1.13371), libc6 (>= 2.14), libgcc1 (>= 1:3.0), libpython3.5 (>= 3.5.0~b1), libstdc++6 (>= 5.2), python3 (<< 3.6), python3 (>= 3.5~), python3:any (>= 3.3.2-2~)```

The only dependency for python in elektra-bin is btw the find-tools script.

**Comment by markus2330** [comment]
Does #1452 fix the issue?

**Comment by markus2330** [comment]
Continuing the discussion from #1452 here.

Can you check for `static` how it was upstream? We should either remove the man page link or add the static build.

On jessie it does not build anymore: `dpkg-checkbuilddeps: Unmet build dependencies: libgit2-dev (>= 0.24.1)`. Any idea how we could add the dep for stretch only? Backporting it is not trivial, it needs `debhelper (>= 9.20160114)`, but jessie has `9.20150101`. But maybe you find a solution for backporting it?

Btw. what do you think to write lintian suppressions for the current warnings? Then we would know when no issues are added?

**Comment by reox** [comment]
mhhh how can you specify a different rules, control and install file for different releases? I think the easiest way is to remove the dependency for libgit on jessie, but that implies changing the above mentioned files.

**Comment by markus2330** [comment]
Isn't there a way to make the absence of a file to be installed not an error? (Optionally installed parts?) Or can we move gitresolver in a separate package that is only built on stretch?

Did you look into the static build?

**Comment by reox** [comment]
I have no idea ;) I need to investigate that. These are problems I did not encountered before, as i always build for a specific release only.

The static build was removed, because it was not enabled in the original debian package: https://github.com/reox/libelektra/commit/42fbe545c5a1d1b4821729f5bfbe2410fcdf41b8#diff-d2b2229a977ef7e99780f2207c29b503R12 
Does the static build flag changes anything else beside creating kdb-static? Maybe it was disabled for a reason... I also need to investigate that

**Comment by markus2330** [comment]
Thanks for looking into it! I temporarily removed the libgit dep so that the build does not fail. So it is not urgent, the zsh/bash completion is certainly more wanted ;)

> always build for a specific release only

Maybe backporting all deps is the better approach anyway?

> Does the static build flag changes anything else beside creating kdb-static?

It also builds `elektra-static`, a static variant of the Elektra library. The static build is not completely static, some plugins  have dynamic deps also in the static build. So for a build with all plugins the static build might be useless anyway. So if it was deactivated, we can keep it deactivated.

**Comment by markus2330** [comment]
All test cases including testmod_crypto_openssl testcase now pass flawlessly! Thank you, great job!

```
> kdb run_all
run_all RESULTS: 129 test(s) done 0 error(s).
```
