### ISSUE TITLE
Build fails on OpenBSD

### ISSUE THREAD

**Issue by nd2s** [ElektraInitiative/libelektra#650]
Using the `cmake ..; make` method:

```
phoenix@puffy build $ make -j9
Scanning dependencies of target exporttranslations
[  0%] Building CXX object src/error/CMakeFiles/exporttranslations.dir/parser.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
In file included from /home/phoenix/libelektra/src/error/parser.cpp:9:
/home/phoenix/libelektra/src/error/parser.hpp:29: error: expected ';' before 'override'
/home/phoenix/libelektra/src/error/parser.hpp:33: error: expected `;' before '}' token
/home/phoenix/libelektra/src/error/parser.hpp: In constructor 'parse_error::parse_error(std::string, int)':
/home/phoenix/libelektra/src/error/parser.hpp:21: error: 'move' is not a member of 'std'
/home/phoenix/libelektra/src/error/parser.hpp: At global scope:
/home/phoenix/libelektra/src/error/parser.hpp:35: error: 'parse_t' was not declared in this scope
/home/phoenix/libelektra/src/error/parser.hpp:35: error: '>>' should be '> >' within a nested template argument list
*** Error 1 in . (src/error/CMakeFiles/exporttranslations.dir/build.make:88 'src/error/CMakeFiles/exporttranslations.dir/parser.cpp.o': cd /...)
*** Error 2 in . (CMakeFiles/Makefile2:1284 'src/error/CMakeFiles/exporttranslations.dir/all')
*** Error 2 in /home/phoenix/libelektra/build (Makefile:161 'all')
```

**Comment by markus2330** [comment]
Thanks for reporting!

Elektra was already reported to work for OpenBSD. #452 tells you have to use egcc/eg++ and libestdc++

Would be great to hear if it works for you!

**Comment by markus2330** [comment]
@tom-wa @petermax2 was there anything that did not work on OpenBSD, how far did you test it?

**Comment by petermax2** [comment]
c282676f99775735b3e09f90c7bd3e754026f877 compiles in OpenBSD 5.9 with egcc 4.9.3. Not all the unit tests pass tough.

**Comment by markus2330** [comment]
Can you create issues for the non-passing unit tests?

**Comment by petermax2** [comment]
See
- #651
- #652
- #653
- #654
- #655
- #656
- #657
- #658
- #659

**Comment by markus2330** [comment]
Thank you, most are related to simpleini, so better to not include this plugin for now.

**Comment by nd2s** [comment]
Stupid question: where do I get `eg++` and `libestdc++`? `egcc` is in the `gcc` package, the other ones are non-existent (did a `pkg_info -E eg++` without any results).

**Comment by petermax2** [comment]
Not every mirror provides (e)gcc-4.9.3. try something like http://ftp.hostserver.de/pub/OpenBSD/5.9/packages/amd64/gcc-4.9.3p3.tgz

**Comment by nd2s** [comment]
@petermax2 I meant I have the `gcc` package, but there is no `eg++` in there, only `egcc`.

**Comment by petermax2** [comment]
It may be contained in http://ftp.hostserver.de/pub/OpenBSD/5.9/packages/amd64/g%2b%2b-4.9.3p3.tgz

I can not remember where I downloaded the pkg from. But I do remeber that many mirrors did not provide eg++.

**Comment by markus2330** [comment]
@nd2s can you drop us which lines worked?

@petermax2 can you add it to doc/COMPILE.md then?

**Comment by petermax2** [comment]
@markus2330 mirrors change from time to time. I think the user should be capable of installing the correct compiler for his/her system. Other than egcc/eg++ there is no difference in compiling Elektra in OpenBSD.

**Comment by nd2s** [comment]
@petermax2 So far I've never had a package missing. I think you selected crappy mirrors to begin with. :)

So, I can confirm compilation works. With tons of ugly compiler warnings, and linker security warnings about use of `sprintf`, `vsprintf`, `strcat`, `strcpy` and such (should be fixed). 

What's important to document is that one has to install packages `gcc` and `g++` - that was the hard thing to find out, not just the compilers' binary names. Then compile with ` CC=/usr/local/bin/egcc CXX=/usr/local/bin/eg++ make`.

**Comment by markus2330** [comment]
Thank you, I added the information. Please reopen if you find further bugs. I created the new issue #668 for fixing the security build warnings.
