### ISSUE TITLE
Haskell Installation Script?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2186]
scripts/generate-haskell-dependencies is

1. not mentioned anywhere
2. assumes that the build directory must be below the source
3. is not used within scripts/docker/debian/stretch/Dockerfile and maybe other dockerfiles, instead the deps are hardcoded there.
4. the deps are also hardcoded in src/bindings/haskell/README.md
5. emits some errors on my Debian stretch machine:

```
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Main             ( /home/markus/Projekte/Elektra/current/scripts/generate-haskell-dependencies.hs, interpreted )

/home/markus/Projekte/Elektra/current/scripts/generate-haskell-dependencies.hs:15:1: error:
    Failed to load interface for ‘Distribution.Types.Dependency’
    Use -v to see a list of the files searched for.

/home/markus/Projekte/Elektra/current/scripts/generate-haskell-dependencies.hs:16:1: error:
    Failed to load interface for ‘Distribution.Types.PackageId’
    Use -v to see a list of the files searched for.

/home/markus/Projekte/Elektra/current/scripts/generate-haskell-dependencies.hs:17:1: error:
    Failed to load interface for ‘Distribution.Types.PackageName’
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
Prelude> 
<interactive>:1:1: error:
    Variable not in scope: generateHaskellDependencies :: [t0] -> t
Prelude> Leaving GHCi
```

@ingwinlu is there some easy way to execute a file of libelektra's repo during generation of the docker images?

**Comment by e1528532** [comment]
yes i only use this script to generate the dependency list and copy it to the readme then, so this is more or less a feature currently, automating this is a bit cumbersome.

**Comment by markus2330** [comment]
Then at least the script documentation should state its purpose.

And why do I get these errors?

**Comment by e1528532** [comment]
The errors very much look like version issues due to the cabal library used. However i am not sure if this script ever worked on 8.0.1 as i really only used this to generate the dependencies on my macOS ;)

**Comment by markus2330** [comment]
Would be good if the script says so!

Btw. can you also fix the Highlight. It does not make much sense to call it a "Preview" if there is no further work planned :-)

**Comment by e1528532** [comment]
So what i'd do on this matter:
1. where would it be placed? In the bindings readme? in the haskell plugin readme?
2. fixing this
3. though it could be included in the image creation process theoretically, that'd be additional effort and right now i think its much easier to have this manually assuming that there won't be too many people trying to create further haskell plugins to make it worth the effort
4. Yes, like said, i considered automating this but decided its simple enough to do manually for now unless suddenly people want to build a lot of haskell plugins ;)
5. try to add the debian compatibility if easily possible, should be just some macros in theory
Also i'll call it prototype than preview in the release notes

**Comment by markus2330** [comment]
> where would it be placed? In the bindings readme? in the haskell plugin readme?

The location of the script is okay. The reference to the script could be in some README explaining how developers can upgrade the dependencies. Maybe in the README of the Haskell binding.

> unless suddenly people want to build a lot of haskell plugins ;)

You never know :smile: 

> try to add the debian compatibility if easily possible

Thank you.

**Comment by e1528532** [comment]
this has been adressed in #2194
