### PR TITLE
jUnit tests for JNA binding + code docs + small bugfixes

### PR DESCRIPTION
**Pull request by Namoshek**
Most stuff should work now as expected. I updated the code docs to contain all important information of the c-docs and split the updates into single commits.

### CODE REVIEW

File: src/bindings/jna/elektra/test/README.md [hunk 1]
```diff
@@ -0,0 +1,10 @@
+Unit tests can be run after importing jUnit, JNA and the elektra java library into a project (eclipse, netbeans, intelliJ, ...).
+
+It should also be possible to run the tests by command line:
+1) Compile the library and tests (run in "elektra" directory):
```
Comment (markus2330) [inline src/bindings/jna/elektra/test/README.md]: Can you give full path src/bindings/jna/elektra here`

When I do:
```
cd src/bindings/jna/elektra
javac -cp .:/usr/share/java/jna.jar:/usr/share/java/junit.jar *.java plugin/*.java test/*.java 
test/AllTests.java:3: error: package org.junit.runner does not exist
import org.junit.runner.RunWith;
                       ^
test/AllTests.java:4: error: package org.junit.runners does not exist
import org.junit.runners.Suite;
                        ^
test/AllTests.java:5: error: package org.junit.runners.Suite does not exist
import org.junit.runners.Suite.SuiteClasses;
```

What are the requirements of the jars?
It seems to work with junit 4.8. This should be specified here, too.

**Comment by markus2330** [comment]
Looks very nice, thank you! Please do some updates on the README.md and it should be fine.

**Comment by markus2330** [comment]
Thank you, nicely done!
