### PR TITLE
GLIB changes

### PR DESCRIPTION
**Pull request by manuelm**
See #3162
See #3171

### CODE REVIEW

**Comment by markus2330** [comment]
Looks good, please write release notes.

> internal change only

I do not know what you mean, this is a change in the public glib API.

**Comment by manuelm** [comment]
> I do not know what you mean, this is a change in the public glib API.

No it's not. No signature changes. No changes in any tests.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
A test fails in Travis:

```
60/254 Test  #57: testio_glib .................................***Failed    5.08 sec

BINDING TEST-SUITE

==================

test basics

test idle

test timer

testTimerShouldCallbackOnce (warning): measured 316ms, expected 250ms - deviation 66ms.

testTimerShouldCallbackAtIntervals (warning): measured 343ms, expected 250ms - deviation 93ms.

testTimerShouldCallbackAtIntervals (warning): measured 322ms, expected 250ms - deviation 72ms.

testTimerShouldCallbackAtIntervals (warning): measured 338ms, expected 250ms - deviation 88ms.

../src/bindings/io/test/test_timer.c:273: error in testTimerShouldChangeInterval: timer was not called the required amount of times

test file descriptor

test mix
```

**Comment by manuelm** [comment]
I looked at the file. It's not related. It isn't using the glib bindings at all.

**Comment by Chemin1** [comment]
> edit2: The failure in jenkins is nonsense as well. Just merge as-is.

I've never seen this test case fail before and cannot find it in #2967. Maybe we should add it there.

```
 27/134 MemCheck  #23: testcpp_contextual_thread ........***Exception: Other  2.59 sec
Running main() from /opt/gtest/googletest/src/gtest_main.cc
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from test_contextual_thread
[ RUN      ] test_contextual_thread.instanciation

/home/jenkins/workspace/libelektra_PR-3168-L5JHIPUUQR3TWFGKHQIDK6HHW6QAMSQXWJC5ZUZMBLDMLTYA2ENA@2/src/bindings/cpp/tests/testcpp_contextual_thread.cpp:70: Failure

Expected equality of these values:
  ks.lookup ("user/hello").getString ()
    Which is: "8"
  "5"
terminate called without an active exception

```

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
@ingwinlu So you could not measure any degradation of performance?

**Comment by markus2330** [comment]
Thank you!
