### PR TITLE
ASAN: support on clang and fixed GIR buildin with UBSAN

### LINKED ISSUE #786: gir does not build with clang sanitizer
With 702cd0cfd025c313e5e165af5394a83fcf01959a one can easily enable [undefinied behavior sanitizer](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html).

gi/gsettings does not build then.
gir:

```
g-ir-scanner: compile: cc -Wno-deprecated-declarations -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wall -I/home/markus/Projekte/Elektra/build-debug-all/src/include -I/home/markus/Projekte/Elektra/libelektra/src/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -c -o /home/markus/Projekte/Elektra/build-debug-all/src/bindings/gi/tmp-introspectOyYBPD/GElektra-4.0.o /home/markus/Projekte/Elektra/build-debug-all/src/bindings/gi/tmp-introspectOyYBPD/GElektra-4.0.c
g-ir-scanner: link: cc -o /home/markus/Projekte/Elektra/build-debug-all/src/bindings/gi/tmp-introspectOyYBPD/GElektra-4.0 -Wall /home/markus/Projekte/Elektra/build-debug-all/src/bindings/gi/tmp-introspectOyYBPD/GElektra-4.0.o -L. -Wl,-rpath=. -Wl,--no-as-needed -lgelektra-4.0 -L/home/markus/Projekte/Elektra/build-debug-all/lib -Wl,-rpath=/home/markus/Projekte/Elektra/build-debug-all/lib -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0
/home/markus/Projekte/Elektra/build-debug-all/lib/libelektra-core.so.4: undefined reference to `__ubsan_handle_negate_overflow'
/home/markus/Projekte/Elektra/build-debug-all/lib/libgelektra-4.0.so: undefined reference to `__ubsan_handle_type_mismatch'
/home/markus/Projekte/Elektra/build-debug-all/lib/libelektra-core.so.4: undefined reference to `__ubsan_handle_out_of_bounds'
/home/markus/Projekte/Elektra/build-debug-all/lib/libelektra-core.so.4: undefined reference to `__ubsan_handle_sub_overflow'
/home/markus/Projekte/Elektra/build-debug-all/lib/libelektra-core.so.4: undefined reference to `__ubsan_handle_mul_overflow'
/home/markus/Projekte/Elektra/build-debug-all/lib/libgelektra-4.0.so: undefined reference to `__ubsan_handle_add_overflow'
/home/markus/Projekte/Elektra/build-debug-all/lib/libgelektra-4.0.so: undefined reference to `__ubsan_handle_nonnull_arg'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['cc', '-o', '/home/markus/Projekte/Elektra/build-debug-all/src/bindings/gi/tmp-introspectOyYBPD/GElektra-4.0', '-Wall', '/home/markus/Projekte/Elektra/build-debug-all/src/bindings/gi/tmp-introspectOyYBPD/GElektra-4.0.o', '-L.', '-Wl,-rpath=.', '-Wl,--no-as-needed', '-lgelektra-4.0', '-L/home/markus/Projekte/Elektra/build-debug-all/lib', '-Wl,-rpath=/home/markus/Projekte/Elektra/build-debug-all/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0']' returned non-zero exit status 1

```

gsettings:

```
g-ir-scanner: compile: cc -Wno-deprecated-declarations -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wall -I/home/markus/Projekte/Elektra/build-64/src/include -I/home/markus/Projekte/Elektra/libelektra/src/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -c -o /home/markus/Projekte/Elektra/build-64/src/bindings/gi/tmp-introspectJtemBT/GElektra-4.0.o /home/markus/Projekte/Elektra/build-64/src/bindings/gi/tmp-introspectJtemBT/GElektra-4.0.c
Linking C shared library ../../../lib/libelektrasettings.so
g-ir-scanner: link: cc -o /home/markus/Projekte/Elektra/build-64/src/bindings/gi/tmp-introspectJtemBT/GElektra-4.0 -Wall /home/markus/Projekte/Elektra/build-64/src/bindings/gi/tmp-introspectJtemBT/GElektra-4.0.o -L. -Wl,-rpath=. -Wl,--no-as-needed -lgelektra-4.0 -L/home/markus/Projekte/Elektra/build-64/lib -Wl,-rpath=/home/markus/Projekte/Elektra/build-64/lib -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0
/home/markus/Projekte/Elektra/build-64/lib/libelektra-core.so.4: undefined reference to `__ubsan_handle_negate_overflow'
/home/markus/Projekte/Elektra/build-64/lib/libgelektra-4.0.so: undefined reference to `__ubsan_handle_type_mismatch'
/home/markus/Projekte/Elektra/build-64/lib/libelektra-core.so.4: undefined reference to `__ubsan_handle_out_of_bounds'
/home/markus/Projekte/Elektra/build-64/lib/libelektra-core.so.4: undefined reference to `__ubsan_handle_sub_overflow'
/home/markus/Projekte/Elektra/build-64/lib/libelektra-core.so.4: undefined reference to `__ubsan_handle_mul_overflow'
/home/markus/Projekte/Elektra/build-64/lib/libgelektra-4.0.so: undefined reference to `__ubsan_handle_add_overflow'
/home/markus/Projekte/Elektra/build-64/lib/libgelektra-4.0.so: undefined reference to `__ubsan_handle_nonnull_arg'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['cc', '-o', '/home/markus/Projekte/Elektra/build-64/src/bindings/gi/tmp-introspectJtemBT/GElektra-4.0', '-Wall', '/home/markus/Projekte/Elektra/build-64/src/bindings/gi/tmp-introspectJtemBT/GElektra-4.0.o', '-L.', '-Wl,-rpath=.', '-Wl,--no-as-needed', '-lgelektra-4.0', '-L/home/markus/Projekte/Elektra/build-64/lib', '-Wl,-rpath=/home/markus/Projekte/Elektra/build-64/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0']' returned non-zero exit status 1
```

seems like g-ir-scanner does not pass CMAKE_SHARED_LINKER_FLAGS`

Workaround is to not use `ALL`, `GI` or `gsettings` bindings, e.g.:

```
~e/scripts/configure-debian -DCMAKE_C_COMPILER=clang-3.8 -DCMAKE_CXX_COMPILER=clang++-3.8 -DBINDINGS="cpp" -DENABLE_DEBUG=ON ~e && make -j 5 && DESTDIR=D make install -j 5
```

### LINKED ISSUE #801: Provide cmake option to compile with address sanitizer
- http://clang.llvm.org/docs/AddressSanitizer.html
  #788

### PR DESCRIPTION
**Pull request by raetiacorvus**
This commit adds support for llvm/clang adress sanitizer.
It can be can only be enabled in combination with debug on.
e.g. `-DENABLE_DEBUG=ON -DENABLE_ASAN=ON` Fixes #801
It also fixes problems when compiling GI bindings with the undefined
behavior sanitizer by passing the corresponding libraries (-lubsan
-lasan). Fixes #786

### CODE REVIEW

**Comment by markus2330** [comment]
I would prefer that ENABLE_DEBUG and ENABLE_ASAN work independently.

Is it really required to have -fsanitize=undefined -fsanitize=integer set so that ASAN works?

**Comment by sirblackheart** [comment]
> Is it really required to have -fsanitize=undefined -fsanitize=integer set so that ASAN works?

No we can let it work independently. I was waiting on your opinion on this mater anyway.

**Comment by sirblackheart** [comment]
We could make it available as a general option as it should be possible to use it even with gcc as long as llvm/clang is installed.

**Comment by markus2330** [comment]
It is always good to avoid dependencies between options. Its confusing and error-prone.

I expected that ENABLE_ASAN is meant to be compiler-independent. So everyone can step up and write support for other compilers.

E.g. ENABLE_COVERAGE  is compiler-independent, but currently only does something when gcc is used.

**Comment by sirblackheart** [comment]
GCC supports the `-fsanitize=address`  since [4.8](https://gcc.gnu.org/gcc-4.8/changes.html).
I probably just misunderstood, it seems they actually integrated the ASAN from LLVM into GCC so yes it should be compiler independent as long as they support the `-fsanitize=address` option.

**Comment by markus2330** [comment]
Then please set -fsanitize=address for both gcc and clang if ENABLE_ASAN was set.

**Comment by sirblackheart** [comment]
I am running in some issues with GCC end ASAN enabled:
```
[ 41%] Linking CXX executable ../../../bin/testmod_type
/usr/bin/ld: ../../../lib/libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
/usr/lib/../lib/libpthread.so.0: error adding symbols: DSO missing from command line
```

**Comment by sirblackheart** [comment]
It also looks like i still need to handle libasan selection correctly

**Comment by sirblackheart** [comment]
> Then please set -fsanitize=address for both gcc and clang if ENABLE_ASAN was set.
should work now.

File: cmake/ElektraCompiling.cmake [hunk 1]
```diff
@@ -61,10 +61,27 @@ if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
...
 endif()
 
+if (ENABLE_ASAN)
+	set (EXTRA_FLAGS "${EXTRA_FLAGS} -fsanitize=address -fno-omit-frame-pointer")
+	set (ASAN_LIBRARY "-lasan") #this is needed for GIR to put asan in front
+	if (CMAKE_COMPILER_IS_GNUCXX)
+		set (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fsanitize=address")
+		# this is currently a workaround so gtests compile with ASAN
+		#TODO someone with expertise migrate this into LibAddTest
+		set (COMMON_FLAGS "${COMMON_FLAGS} -lpthread")
```
Comment (sirblackheart) [inline cmake/ElektraCompiling.cmake]: this is rather a workaround for the gcc asan problem by explicitly adding -lpthread. Someone with expertise in the gtest phtread setup for elektra should probably take a look if there is a better way to handle this.

File: cmake/ElektraCompiling.cmake [hunk 2]
```diff
@@ -61,10 +61,27 @@ if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
 
 	if (ENABLE_DEBUG)
 		set (EXTRA_FLAGS "${EXTRA_FLAGS} -fsanitize=undefined -fsanitize=integer")
-		set (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fsanitize=undefined -fsanitize=integer")
+		set (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -lubsan")
```
Comment (markus2330) [inline cmake/ElektraCompiling.cmake]: Are you sure this is identical? I cannot find it the man page of gcc-4.9.1. It might be some internal stuff not to be used in front-ends?

File: cmake/ElektraCompiling.cmake (hunk 1 above)
Comment (markus2330) [inline cmake/ElektraCompiling.cmake]: You need:
```
find_package(Threads)
and then you can add ${CMAKE_THREAD_LIBS_INIT} to linker flags
```

Are you sure it should be in COMMON_FLAGS?

File: cmake/ElektraCompiling.cmake (hunk 2 above)
Comment (sirblackheart) [inline cmake/ElektraCompiling.cmake]: You have not enabled `ubsan` in `gcc` and not asked me to move that away from clang and debug only `asan`. So probably you should look into the llvm/cland doc. All I can tell you is that GIR now compiles fine with this linker flag as opposed to the one you set.

File: cmake/ElektraCompiling.cmake (hunk 1 above)
Comment (sirblackheart) [inline cmake/ElektraCompiling.cmake]: > find_package(Threads)
> and then you can add ${CMAKE_THREAD_LIBS_INIT} to linker flags

This is already used in LibAddTest and i still run into compiling issues. Adding it globally fixed theme. Those the question if someone with expertise in this can solve this better.

File: cmake/ElektraCompiling.cmake (hunk 2 above)
Comment (markus2330) [inline cmake/ElektraCompiling.cmake]: Ahh, sorry, github did not show me enough context and I thought it would be a place for both gcc+clang.

File: cmake/ElektraCompiling.cmake (hunk 1 above)
Comment (markus2330) [inline cmake/ElektraCompiling.cmake]: My suggestion was to not directly use `-lpthread` (that is not portable), but to use `${CMAKE_THREAD_LIBS_INIT}` instead. With the change we can merge the PR.

If -fsanitize=address generates code that requires to be linked with `${CMAKE_THREAD_LIBS_INIT}` then we will have to do this, someone with more expertise will also not be able to change this fact.

If its needed can be found out by compiling and linking it. No expertise required here.

Comment (markus2330) [inline cmake/ElektraCompiling.cmake]: Maybe @mpranj has time to set up a new build job that uses clang with ENABLE_ASAN?

Comment (sirblackheart) [inline cmake/ElektraCompiling.cmake]: I was asking for expertise in regard of -lpthread in combination of the gtests as this was the place i got [problems](https://github.com/ElektraInitiative/libelektra/pull/803#issuecomment-226262269) with the linking on gcc. As some internet posts suggest this could be a problem of linking flag order. Using it for general linking surely solves the problem but a more granular solution would have been nicer.

Comment (markus2330) [inline cmake/ElektraCompiling.cmake]: So you say that it actually is *not* needed globally but only gtest suddenly does not link with ENABLE_ASAN? Then we should not enable it globally, but fix the linking order for the gtests.

We had a issue with pthread and gtest already here: https://github.com/ElektraInitiative/libelektra/issues/737

You can either find out the exact dependencies of every library and do a topological sort or you can simply guess and shuffle around the linker flags until it works (as done in #737)

Comment (mpranj) [inline cmake/ElektraCompiling.cmake]: Do I understand this correctly: A new build job with ENABLE_ASAN is **not** needed any more?

Comment (sirblackheart) [inline cmake/ElektraCompiling.cmake]: No it will be needed once i fix the linking granularity and this pr get merged.

Comment (markus2330) [inline cmake/ElektraCompiling.cmake]: Exactly, it *will* be needed ;) The *not* needed referred to the global pthread linker flag ;) Let us use #160 in future to avoid such confusions.

It would also be interesting to have it before the PR is merged: we can trigger the build job from here.

**Comment by mpranj** [comment]
jenkins build clang-asan please

File: cmake/ElektraCompiling.cmake (hunk 1 above)
Comment (sirblackheart) [inline cmake/ElektraCompiling.cmake]: So i investigated this issue further and tried to solve it for gtest but that only moved the problem to the next library using `pthread`. This [bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69443) explains this issue for gcc further. According to it, clang solves it by linking to `pthread` when `-fsanitize=address` is passed, gcc does not. So i propose to use the solution from the the bug report to pass` -Wl,--as-needed ${CMAKE_THREAD_LIBS_INIT}` as last compiler flag.

**Comment by sirblackheart** [comment]
jenkins build clang-asan please

**Comment by markus2330** [comment]
Looks good, everything builds now.

**Comment by sirblackheart** [comment]
jenkins build clang-asan please

**Comment by sirblackheart** [comment]
all but the clang-asan, but that will need some suppression files #788

**Comment by markus2330** [comment]
@raetiacorvus Thanks, great job! I merged it because clang with ENABLE_DEBUG is broken and ENABLE_ASAN seems like a very nice solution!
