### ISSUE TITLE
fail build with gcc5.3

### ISSUE THREAD

**Issue by sl1pkn07** [ElektraInitiative/libelektra#432]
[ 39%] Linking CXX executable ../../../bin/testmod_type
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o: In function `elektra::MType<short>::~MType()':
    testmod_type.cpp:(.text._ZN7elektra5MTypeIsED2Ev[_ZN7elektra5MTypeIsED5Ev]+0x8): undefined reference to `elektra::Type::~Type()'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o: In function `elektra::MType<short>::~MType()':
    testmod_type.cpp:(.text._ZN7elektra5MTypeIsED0Ev[_ZN7elektra5MTypeIsED5Ev]+0xc): undefined reference to `elektra::Type::~Type()'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o: In function `elektra::MType<unsigned short>::~MType()':
    testmod_type.cpp:(.text._ZN7elektra5MTypeItED2Ev[_ZN7elektra5MTypeItED5Ev]+0x8): undefined reference to `elektra::Type::~Type()'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o: In function `elektra::MType<unsigned short>::~MType()':
    testmod_type.cpp:(.text._ZN7elektra5MTypeItED0Ev[_ZN7elektra5MTypeItED5Ev]+0xc): undefined reference to `elektra::Type::~Type()'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o: In function `elektra::MType<int>::~MType()':
    testmod_type.cpp:(.text._ZN7elektra5MTypeIiED2Ev[_ZN7elektra5MTypeIiED5Ev]+0x8): undefined reference to `elektra::Type::~Type()'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o:testmod_type.cpp:(.text._ZN7elektra5MTypeIiED0Ev[_ZN7elektra5MTypeIiED5Ev]+0xc): more undefined references to `elektra::Type::~Type()' follow
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o:(.rodata._ZTIN7elektra7AnyTypeE[_ZTIN7elektra7AnyTypeE]+0x10): undefined reference to `typeinfo for elektra::Type'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o:(.rodata._ZTIN7elektra9EmptyTypeE[_ZTIN7elektra9EmptyTypeE]+0x10): undefined reference to `typeinfo for elektra::Type'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o:(.rodata._ZTIN7elektra10StringTypeE[_ZTIN7elektra10StringTypeE]+0x10): undefined reference to `typeinfo for elektra::Type'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o:(.rodata._ZTIN7elektra6FSTypeE[_ZTIN7elektra6FSTypeE]+0x10): undefined reference to `typeinfo for elektra::Type'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o:(.rodata._ZTIN7elektra5MTypeIsEE[_ZTIN7elektra5MTypeIsEE]+0x10): undefined reference to `typeinfo for elektra::Type'
    CMakeFiles/testmod_type.dir/testmod_type.cpp.o:(.rodata._ZTIN7elektra5MTypeItEE[_ZTIN7elektra5MTypeItEE]+0x10): more undefined references to `typeinfo for elektra::Type' follow
    ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::UnitTestImpl::~UnitTestImpl()':
    gtest-all.cc:(.text+0xd21a): undefined reference to `pthread_getspecific'
    gtest-all.cc:(.text+0xd234): undefined reference to `pthread_key_delete'
    gtest-all.cc:(.text+0xd42a): undefined reference to `pthread_getspecific'
    gtest-all.cc:(.text+0xd444): undefined reference to `pthread_key_delete'
    ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::UnitTestImpl::UnitTestImpl(testing::UnitTest*)':
    gtest-all.cc:(.text+0xe5a0): undefined reference to `pthread_key_create'
    gtest-all.cc:(.text+0xe790): undefined reference to `pthread_key_create'
    ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::~ThreadLocal()':
    gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED2Ev[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED5Ev]+0x1b): undefined reference to `pthread_getspecific'
    gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED2Ev[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED5Ev]+0x30): undefined reference to `pthread_key_delete'
    ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::~ThreadLocal()':
    gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED2Ev[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED5Ev]+0x1e): undefined reference to `pthread_getspecific'
    gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED2Ev[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED5Ev]+0x35): undefined reference to `pthread_key_delete'
    ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::GetOrCreateValue() const':
    gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv]+0x24): undefined reference to `pthread_getspecific'
    gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv]+0x146): undefined reference to `pthread_setspecific'
    ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::GetOrCreateValue() const':
    gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv]+0x1c): undefined reference to `pthread_getspecific'
    gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv]+0x73): undefined reference to `pthread_setspecific'
    collect2: error: ld returned 1 exit status
    src/plugins/type/CMakeFiles/testmod_type.dir/build.make:101: recipe for target 'bin/testmod_type' failed
    make[2]: *** [bin/testmod_type] Error 1
    CMakeFiles/Makefile2:6286: recipe for target 'src/plugins/type/CMakeFiles/testmod_type.dir/all' failed
    make[1]: *** [src/plugins/type/CMakeFiles/testmod_type.dir/all] Error 2
    Makefile:160: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by markus2330** [comment]
Thank you for reporting!

If it is the clang error `src/bindings/cpp/examples/cpp_example_userexception.cpp:60:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'basic_string<char, std::char_traits<char>, std::allocator<char> >' to 'const kdb::KeyNotFoundException' for 1st argument
class KeyNotFoundException : public Exception` it will be fixed shortly, otherwise please post the error message.

**Comment by sl1pkn07** [comment]
sorry, i edited the message whit the error, and no, is with GCC 5.3.0

**Comment by markus2330** [comment]
Thanks for the message. Can you also give me the cmake command-line? In particular I am interested if you use an external gtest-all.cc? For some reason it seems to depent on pthread. I will try to get an `gcc 5.3` to reproduce it then.

**Comment by sl1pkn07** [comment]
export JAVA_HOME="/usr/lib/jvm/default"  
    cmake ../elektra \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_FULL=OFF \
        -DBUILD_STATIC=OFF \
        -DTOOLS=ALL \
        -DPLUGINS=ALL \
        -DBINDINGS=ALL
      make -j1

CMakeCache.txt: http://sl1pkn07.wtf/paste/view/5ddf92a3

**Comment by markus2330** [comment]
Thank you! I could reproduce it. Seems like there is more than one issue when g++5.3 is used. I will fix them soon.

**Comment by sl1pkn07** [comment]
now build ok


thanks!

ap! Happy new year! XD

**Comment by markus2330** [comment]
Thanks for reporting it!
happy new year!
