### ISSUE TITLE
Ambiguity in the C++ KeySet varargs constructors

### ISSUE THREAD

**Issue by pinotree** [ElektraInitiative/libelektra#42]
Currently the C++ bindings of KeySet provides, among the others, two contructors with varargs:
```c++
	inline explicit KeySet(size_t alloc, va_list ap);
	inline explicit KeySet(size_t alloc, ...);
```
the problem is that on some architectures `va_list` is represented as `void*` as public type, which makes the two constructor ambiguous when called with `alloc` greater than 0 and no additional arguments. In such case, the `va_list` version gets used, causing `ksVNew` to try to read arguments from a null (or garbage) `ap`.

The following patch for `src/bindings/cpp/tests/testcpp_ks.cpp`
```diff
@@ -821,6 +821,18 @@ void test_duplicate()
        // ks4.toStream(stdout, 0);
 }

+void test_alloc_no_keys()
+{
+       cout << "testing test_alloc_no_keys" << endl;
+
+       KeySet ks (5,
+               KS_END);
+       succeed_if (ks.size() == 5, "size not correct");
+
+       KeySet ks2 (ks);
+       succeed_if (ks2.size() == 5, "size not correct");
+}
+

 int main()
 {
@@ -844,6 +856,7 @@ int main()
        test_ksrelease();
        test_lookuppop();
        test_duplicate();
+       test_alloc_no_keys();

        cout << endl;
        cout << "test_key RESULTS: " << nbTest << " test(s) done. " << nbError << " error(s)." << endl;
```
is enough to trigger the issue on e.g. mips(el) or hppa. Currently this is exposed by the lua and python bindings, since all do:
```c++
  KeySet(size_t alloc) {
    return new kdb::KeySet(alloc, KS_END);
  }
```
In those it can be easily worked around by adding the `KS_END` marker a second time (making them really as vararg), but of course it wouldn't fix the issue with the C++ contructors of KeySet.

**Comment by markus2330** [comment]
@manuelm: It seems like that the fix is not portable at all:

    if (va && alloc != 1)

does not compile on armv6 with gcc4.7:

```
/home/markus/elektra/libelektra/src/libelektra/keyset.c: In function ‘ksVNew’:
/home/markus/elektra/libelektra/src/libelektra/keyset.c:229:6: error: used struct type value where scalar is required
```

Is there still a problem when I remove the `va &&`? There has to be a way in the binding to always pass 0 as first argument when no va_args are present.

**Comment by markus2330** [comment]
(The same problem is in the C++ binding)

**Comment by manuelm** [comment]
> There has to be a way in the binding to always pass 0 as first argument when no va_args are present.
Like https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/swig/python3/kdb.i#L217 or https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/swig/lua/kdb.i#L249 ?

**Comment by manuelm** [comment]
I'll see if I can come up with another solution.

**Comment by markus2330** [comment]
Hello,

you wrote:
> Like
> https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/s
> wig/python3/kdb.i#L217 or
> https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/s
> wig/lua/kdb.i#L249 ?

If its terminated with KS_END its ok.

best regards

**Comment by manuelm** [comment]
I think our options are:

* add some macro or cmake magic and check if va_list is a pointer or a struct. only do the check if it's a pointer.
* add #if \_\_LINUX_ARM_ARCH__ to src/libelektra/keyset.c and don't check the va_list on arm
* make KeySet::KeySet unambiguous by renaming the constructor to e.g. fromVA(...). API consumers have to do: KeySet ks(); ks.fromVA(size, va_list);
* make KeySet::KeySet unambiguous by adding a dummy variable between alloc and va_list
* just remove the constructor

The last three options will break API __and__ will cause segfaults unless API consumers change their code as well. Since we make the two constructors unambiguous, the compiler will just use the other constructor without any warning.

The first and 2nd are my preferred choices.

**Comment by manuelm** [comment]
I tried the first option and failed. va_list aka __gnuc_va_list is always a struct. On some platforms the struct consists of a single pointer, on others it has a few more member. So the struct check doesn't make much sense.

To finally fix this I'm proposing the following:
* Create a copy of the KeySet::KeySet(size_t alloc, va_list ap) constructor and name it KeySet::fromVA
* Make the constructor only available to x86 and x86_64 and add deprecation warnings

@markus2330 any objections?

**Comment by manuelm** [comment]
Something more: Can we please remove -Wno-deprecated-declarations from ElektraCompiling.cmake? That was introduced in 30955ed244dbea35852d4bb64bb2a4f72d0e34b8 but I think it's bad practice to hide warnings. Even if they're no harmless.

**Comment by markus2330** [comment]
Hello,

you wrote:
> Something more: Can we please remove -Wno-deprecated-declarations from
> ElektraCompiling.cmake? That was introduced in
> 30955ed244dbea35852d4bb64bb2a4f72d0e34b8 but I think it's bad practice to
> hide warnings. Even if they're no harmless.

Yeah, we certainly can remove this, thats actually a good Idea!

I think the issue why it was introduced is already solved: The problem was 
that every use of auto_ptr will be warned when compiled with C++11 and 
unique_ptr is not available in C++03.

But now a macro uses the correct one. (At least in many places.)
